model: swin_large_patch4_window12_384
pretrained: true
num_classes: 1572
img_size: 384
batch_size: 16

apex_amp: true


sched: plateau
epochs: 100
patience_epochs: 1
decay_rate: 0.1

eval_metric: loss
